version: '3.8'

services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,z
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'
    networks:
      - payment-processor
      - payment-processor-db

  api01:
    image: quay.io/rhn_support_arolivei/rinha-de-backend-2025-golang:latest
    hostname: api01
    environment:
      - REDIS_ADDR=redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '155MB'
    networks:
      - payment-processor
      - payment-processor-db

  api02:
    image: quay.io/rhn_support_arolivei/rinha-de-backend-2025-golang:latest
    hostname: api02
    environment:
      - REDIS_ADDR=redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '155MB'
    networks:
      - payment-processor
      - payment-processor-db

  redis:
    image: redis:7.2.0-alpine
    hostname: redis
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'
    networks:
      - payment-processor
      - payment-processor-db

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
